#!/bin/bash


if [[ ! -z "$BITRIX_CLI_PHP" ]]; then
  PHP="$BITRIX_CLI_PHP"
else
  PHP=`which php`
  if [[ "$?" != "0" ]]; then
    echo "PHP not found"
    exit 1
  fi
fi

case $1 in
  element)
    # передаем все аргументы, кроме первого
    $PHP "$(dirname "$0")"/bitrix-element.php "${@:2}"
  ;;
  section)
    $PHP "$(dirname "$0")"/bitrix-section.php "${@:2}"
  ;;
  iblock)
    $PHP "$(dirname "$0")"/bitrix-iblock.php "${@:2}"
  ;;
  component)
    $PHP "$(dirname "$0")"/bitrix-component.php "${@:2}"
  ;;
  error)
    $PHP "$(dirname "$0")"/bitrix-error.php "${@:2}"
  ;;
  event)
    $PHP "$(dirname "$0")"/bitrix-event.php "${@:2}"
  ;;
  user)
    $PHP "$(dirname "$0")"/bitrix-user.php "${@:2}"
  ;;
  file)
    $PHP "$(dirname "$0")"/bitrix-file.php "${@:2}"
  ;;
  option)
    $PHP "$(dirname "$0")"/bitrix-option.php "${@:2}"
  ;;
  db)
    $PHP "$(dirname "$0")"/bitrix-db.php "${@:2}"
  ;;
  *)
    echo 'Command not found'
    exit 1
esac
